ALTER TABLE payroll_rows
  ALTER COLUMN total_deductions TYPE DECIMAL(14,2) USING ROUND(total_deductions::NUMERIC, 2);

ALTER TABLE payroll_rows
  ALTER COLUMN pf_er TYPE DECIMAL(14,2) USING ROUND(pf_er::NUMERIC, 2);

ALTER TABLE payroll_rows
  ALTER COLUMN esic_er TYPE DECIMAL(14,2) USING ROUND(esic_er::NUMERIC, 2);

-- FIXED COLUMN NAMES 👇
ALTER TABLE payroll_runs
  ALTER COLUMN "totalPFEE" TYPE DECIMAL(14,2) USING ROUND("totalPFEE"::NUMERIC, 2);

ALTER TABLE payroll_runs
  ALTER COLUMN "totalPFER" TYPE DECIMAL(14,2) USING ROUND("totalPFER"::NUMERIC, 2);