BEGIN;

ALTER TABLE payroll_runs
  ALTER COLUMN total_gross TYPE DECIMAL(14,2) USING ROUND(total_gross::NUMERIC, 2),
  ALTER COLUMN total_net TYPE DECIMAL(14,2) USING ROUND(total_net::NUMERIC, 2);

ALTER TABLE payroll_rows
  ALTER COLUMN gross_earnings TYPE DECIMAL(14,2) USING ROUND(gross_earnings::NUMERIC, 2),
  ALTER COLUMN net_pay TYPE DECIMAL(14,2) USING ROUND(net_pay::NUMERIC, 2),
  ALTER COLUMN pf_ee TYPE DECIMAL(14,2) USING ROUND(pf_ee::NUMERIC, 2),
  ALTER COLUMN esic_ee TYPE DECIMAL(14,2) USING ROUND(esic_ee::NUMERIC, 2);

COMMIT;